#!/bin/sh
#
# Hook script to prevent self-doxxing by looking for phone number
# and address.
# As it relies on regex it's probably going to find false positives
#
# ToDo: Trap only on "real" files and not index IDs, etc.
# 
# To use: Copy to .git/hooks/pre-commit
#

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

PHONE=`git diff --cached $against *.tex| grep -E '[0-9]{3}.{0,2}[0-9]{3}.?[0-9]{4}'`
ADDR=`git diff --cached $against *.tex| grep -E '[0-9]{1,5} [a-zA-Z]{2,14} [a-zA-Z]{1,8}'`

if [ "$PHONE" ] ; then
	echo Error: Phone number not allowed in checkin
	echo Error: $PHONE
	exit 1
fi

if [ "$ADDR" ] ; then
	echo Error: Address number not allowed in checkin
	echo Error: $ADDR
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
#exec git diff-index --check --cached $against --
