name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest 
    container: edgriebel/tinytex-xelatex
    # blang/latex:ubuntu

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: What's there?
      run: ls -la
      #- name: Test xelatex
      #run: latexmk -xelatex Ed_Griebel_CV.tex
