name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest 
    container: edgriebel/tinytex-xelatex

    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: What's there?
      run: ls -la
    - name: test build
      run: make all
    - name: What happened?
      run: ls -lt
    - name: Create release
      run: |
        gh --help
